"""adiciona tabelas de tarifas e servicos adicionais

Revision ID: 268c1ee78dd1
Revises: 72d2d0413dad
Create Date: 2026-09-24 16:43:47.195017

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '268c1ee78dd1'
down_revision: Union[str, None] = '72d2d0413dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###