"""adiciona tabela quartos

Revision ID: 72d2d0413dad
Revises: 1f511b063363
Create Date: 2026-09-21 23:51:46.013730

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72d2d0413dad'
down_revision: Union[str, None] = '1f511b063363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quartos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('preco_diaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_adultos', sa.Integer(), nullable=False),
    sa.Column('max_criancas', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('max_adultos >= 1', name='ck_quartos_max_adultos_positivo'),
    sa.CheckConstraint('max_criancas >= 0', name='ck_quartos_max_criancas_nao_negativo'),
    sa.CheckConstraint('preco_diaria >= 0', name='ck_quartos_preco_nao_negativo'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quartos_hotel_id'), 'quartos', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quartos_hotel_id'), table_name='quartos')
    op.drop_table('quartos')
    # ### end Alembic commands ###
